# Main menu settings
[main]
  align_right = true

# Main Header Menu Links
[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "Publications"
  url = "/publication/"
  weight = 2

[[main]]
  name = "Projects"
  url = "/project/"
  weight = 3

[[main]]
  name = "Talks"
  url = "/talk/"
  weight = 4

[[main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 5

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 6

# Footer Menu Links
[[footer]]
  name = "License"
  title = "License"
  url = "/license/"
  weight = 1
[[footer]]
  name = "Contact"
  title = "Contact form"
  url = "/contact/"
  weight = 2
[[footer]]
  name = "Contributors"
  title = "Contributors"
  url = "/contributors/"
  weight = 3